Algoritmo "multiplicaoProcedimentoComParametro"

procedimento multiplicacao(a,b : inteiro)

var
   resultado: inteiro
   
inicio

   resultado <- a * b

   escreval("O resultado é: ", resultado)

fimprocedimento

Var

   numero1, numero2: inteiro

Inicio

   escreval("Digite o primeiro numero")
   leia(numero1)

   escreval("Digite o segundo numero")
   leia(numero2)

   multiplicacao(numero1, numero2)

Fimalgoritmo